# Preprocessing

In [16]:
import pandas as pd
import numpy as np
import os
os.chdir("/Users/erikgregorywebb/Documents/Python/nba-prediction/Preprocessing/Data")
pd.set_option('display.max_columns', None)

In [17]:
# Bring in the data
df = pd.read_csv("raw.csv")
df.head(3)

,Team,Opponent,Team-Score,Opponent-Score,Win,Date,Time,Location,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,TS%,eFG%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,ORtg,DRtg
0,Cleveland Cavaliers,Washington Wizards,94,84,1,10/30/12,7:00 PM,"Quicken Loans Arena, Cleveland, Ohio",36,79,0.456,7,20,0.350,15,22,0.682,18,36,54,22,7,5,20,21,0.530,0.500,0.253,0.278,46.2,66.7,58.1,61.1,8.0,8.6,18.4,106.9,95.5
1,Dallas Mavericks,Los Angeles Lakers,99,91,1,10/30/12,7:30 PM,"STAPLES Center, Los Angeles, California",40,85,0.471,5,15,0.333,14,18,0.778,9,31,40,22,9,5,11,25,0.533,0.500,0.176,0.212,22.5,67.4,46.5,55.0,9.9,7.8,10.6,108.7,99.9
2,Miami Heat,Boston Celtics,120,107,1,10/30/12,8:00 PM,"AmericanAirlines Arena, Miami, Florida",43,79,0.544,8,16,0.500,26,32,0.813,5,31,36,25,8,5,8,20,0.645,0.595,0.203,0.405,12.8,81.6,46.8,58.1,8.5,8.1,7.9,127.0,113.2

### Create 'Seasons' Variable

In [18]:
# Prepare the data by changing type to date
df.Date = pd.to_datetime(df.Date)

In [19]:
position = len(df.columns)
df['Season'] = ""

for i in range(0, len(df)):
    # 2012-13 Season: October 30, 2012 - June 20, 2013
    if df.iloc[i, 5] >= pd.Timestamp('2012-10-30 00:00:00') and df.iloc[i, 5] <= pd.Timestamp('2013-6-20 00:00:00'):
        df.iloc[i, position] = '2012-13'
    
    # 2013-14 Season: October 29, 2013 - June 15, 2014
    elif df.iloc[i, 5] >= pd.Timestamp('2013-10-29 00:00:00') and df.iloc[i, 5] <= pd.Timestamp('2014-6-15 00:00:00'):
        df.iloc[i, position] = '2013-14'
    
    # 2014-15 Season: October 29, 2014 - June 16, 2015
    elif df.iloc[i, 5] >= pd.Timestamp('2014-10-28 00:00:00') and df.iloc[i, 5] <= pd.Timestamp('2015-6-16 00:00:00'):
        df.iloc[i, position] = '2014-15'
    
    # 2015-16 Season: October 27, 2015 - June 19, 2016
    elif df.iloc[i, 5] >= pd.Timestamp('2015-10-27 00:00:00') and df.iloc[i, 5] <= pd.Timestamp('2016-6-19 00:00:00'):
        df.iloc[i, position] = '2015-16'
    
    # 2016-17 Season: October 25, 2016 - June 12, 2017
    elif df.iloc[i, 5] >= pd.Timestamp('2016-10-25 00:00:00') and df.iloc[i, 5] <= pd.Timestamp('2017-6-12 00:00:00'):
        df.iloc[i, position] = '2016-17'
    else: 
        df.iloc[i, position] = None

In [20]:
# Number of games by Season
df['Season'].value_counts()

2013-14    2624
2016-17    2592
2012-13    2500
2015-16    2500
2014-15    2498
Name: Season, dtype: int64

In [21]:
df.head(3)

,Team,Opponent,Team-Score,Opponent-Score,Win,Date,Time,Location,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,TS%,eFG%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,ORtg,DRtg,Season
0,Cleveland Cavaliers,Washington Wizards,94,84,1,2012-10-30,7:00 PM,"Quicken Loans Arena, Cleveland, Ohio",36,79,0.456,7,20,0.350,15,22,0.682,18,36,54,22,7,5,20,21,0.530,0.500,0.253,0.278,46.2,66.7,58.1,61.1,8.0,8.6,18.4,106.9,95.5,2012-13
1,Dallas Mavericks,Los Angeles Lakers,99,91,1,2012-10-30,7:30 PM,"STAPLES Center, Los Angeles, California",40,85,0.471,5,15,0.333,14,18,0.778,9,31,40,22,9,5,11,25,0.533,0.500,0.176,0.212,22.5,67.4,46.5,55.0,9.9,7.8,10.6,108.7,99.9,2012-13
2,Miami Heat,Boston Celtics,120,107,1,2012-10-30,8:00 PM,"AmericanAirlines Arena, Miami, Florida",43,79,0.544,8,16,0.500,26,32,0.813,5,31,36,25,8,5,8,20,0.645,0.595,0.203,0.405,12.8,81.6,46.8,58.1,8.5,8.1,7.9,127.0,113.2,2012-13

### Create 'Playoff' Game Dummy

In [22]:
position = len(df.columns)
df['Playoff'] = ""

for i in range(0, len(df)):
    # 2013 Playoffs: April 20 - June 20, 2013
    if df.iloc[i, 5] >= pd.Timestamp('2013-4-20 00:00:00') and df.iloc[i, 5] <= pd.Timestamp('2013-6-20 00:00:00'):
        df.iloc[i, position] = 1
    
    # 2014 Playoffs: April 19 - June 15, 2014
    elif df.iloc[i, 5] >= pd.Timestamp('2014-4-19 00:00:00') and df.iloc[i, 5] <= pd.Timestamp('2014-6-15 00:00:00'):
        df.iloc[i, position] = 1
    
    # 2015 Playoffs: April 18 - June 16, 2015
    elif df.iloc[i, 5] >= pd.Timestamp('2015-4-18 00:00:00') and df.iloc[i, 5] <= pd.Timestamp('2015-6-16 00:00:00'):
        df.iloc[i, position] = 1
    
    # 2016 Playoffs: April 16 - June 19, 2016
    elif df.iloc[i, 5] >= pd.Timestamp('2016-4-16 00:00:00') and df.iloc[i, 5] <= pd.Timestamp('2016-6-19 00:00:00'):
        df.iloc[i, position] = 1
    
    # 2017 Playoffs: April 15 - June 12, 2017
    elif df.iloc[i, 5] >= pd.Timestamp('2017-4-15 00:00:00') and df.iloc[i, 5] <= pd.Timestamp('2017-6-12 00:00:00'):
        df.iloc[i, position] = 1
    else: 
        df.iloc[i, position] = 0

In [23]:
df['Playoff'].value_counts()

0    11878
1      836
Name: Playoff, dtype: int64

In [24]:
df.head(3)

,Team,Opponent,Team-Score,Opponent-Score,Win,Date,Time,Location,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,TS%,eFG%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,ORtg,DRtg,Season,Playoff
0,Cleveland Cavaliers,Washington Wizards,94,84,1,2012-10-30,7:00 PM,"Quicken Loans Arena, Cleveland, Ohio",36,79,0.456,7,20,0.350,15,22,0.682,18,36,54,22,7,5,20,21,0.530,0.500,0.253,0.278,46.2,66.7,58.1,61.1,8.0,8.6,18.4,106.9,95.5,2012-13,0
1,Dallas Mavericks,Los Angeles Lakers,99,91,1,2012-10-30,7:30 PM,"STAPLES Center, Los Angeles, California",40,85,0.471,5,15,0.333,14,18,0.778,9,31,40,22,9,5,11,25,0.533,0.500,0.176,0.212,22.5,67.4,46.5,55.0,9.9,7.8,10.6,108.7,99.9,2012-13,0
2,Miami Heat,Boston Celtics,120,107,1,2012-10-30,8:00 PM,"AmericanAirlines Arena, Miami, Florida",43,79,0.544,8,16,0.500,26,32,0.813,5,31,36,25,8,5,8,20,0.645,0.595,0.203,0.405,12.8,81.6,46.8,58.1,8.5,8.1,7.9,127.0,113.2,2012-13,0

### Create 'Home/Away' Dummy

In [25]:
# Brining in data about each team's home location
locations_df = pd.read_csv("locations.csv")
teams = list(locations_df.Team)
locations = list(locations_df.Location)

# Create new 'Home" column 
position = len(df.columns)
df['Home'] = 0

# For each row of the data, determine if the team is playing at home
for i in range(0, len(df)):
    for j in range(0, len(locations)):
        if df.iloc[i, 0] == teams[j] and df.iloc[i, 7] == locations[j]:
            df.iloc[i, position] = 1

In [26]:
# 0 is Away, 1 is Home
df['Home'].value_counts()

0    6391
1    6323
Name: Home, dtype: int64

In [27]:
df.head(3)

,Team,Opponent,Team-Score,Opponent-Score,Win,Date,Time,Location,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,TS%,eFG%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,ORtg,DRtg,Season,Playoff,Home
0,Cleveland Cavaliers,Washington Wizards,94,84,1,2012-10-30,7:00 PM,"Quicken Loans Arena, Cleveland, Ohio",36,79,0.456,7,20,0.350,15,22,0.682,18,36,54,22,7,5,20,21,0.530,0.500,0.253,0.278,46.2,66.7,58.1,61.1,8.0,8.6,18.4,106.9,95.5,2012-13,0,1
1,Dallas Mavericks,Los Angeles Lakers,99,91,1,2012-10-30,7:30 PM,"STAPLES Center, Los Angeles, California",40,85,0.471,5,15,0.333,14,18,0.778,9,31,40,22,9,5,11,25,0.533,0.500,0.176,0.212,22.5,67.4,46.5,55.0,9.9,7.8,10.6,108.7,99.9,2012-13,0,0
2,Miami Heat,Boston Celtics,120,107,1,2012-10-30,8:00 PM,"AmericanAirlines Arena, Miami, Florida",43,79,0.544,8,16,0.500,26,32,0.813,5,31,36,25,8,5,8,20,0.645,0.595,0.203,0.405,12.8,81.6,46.8,58.1,8.5,8.1,7.9,127.0,113.2,2012-13,0,1

### Filter by Season

In [28]:
# Regular Season (Non-Playoff) Games
df_12_13 = df[(df.Season == "2012-13") & (df.Playoff == 0)]
df_13_14 = df[(df.Season == "2013-14") & (df.Playoff == 0)]
df_14_15 = df[(df.Season == "2014-15") & (df.Playoff == 0)]
df_15_16 = df[(df.Season == "2015-16") & (df.Playoff == 0)]
df_16_17 = df[(df.Season == "2016-17") & (df.Playoff == 0)]

In [29]:
# Write to CSV
os.chdir("/Users/erikgregorywebb/Documents/Python/nba-prediction/Clustering/Data")
df_12_13.to_csv("df_12_13.csv", index = False)
df_13_14.to_csv("df_13_14.csv", index = False)
df_14_15.to_csv("df_14_15.csv", index = False)
df_15_16.to_csv("df_15_16.csv", index = False)
df_16_17.to_csv("df_16_17.csv", index = False)
os.chdir("/Users/erikgregorywebb/Documents/Python/nba-prediction")

### Combine & Get Averages

In [30]:
# We can only predict the outcome of a game using features that are measurable BEFORE the game occurs 
# This function takes as inputs a dataframe (i.e. df_12_13) and the number of games desired to form the averages
# and outputs a dataframe where all numerical features (ex. FG, FGA, FG%) are averages. 

def get_averages(dataframe, number_of_games):
    games = []
    
    # For each row of the dataframe, filter and create a new dataframe containing all games
    # played by the team of that row which occured before that game (also including that game)
    # Do the same thing for the opponent
    for i in range(0, len(dataframe)):
        team_df = dataframe[(dataframe.Team == dataframe.iloc[i,0]) & (dataframe.Date <= dataframe.iloc[i,5])].sort_values(by='Date', ascending = True).iloc[-number_of_games:]
        opponent_df = dataframe[(dataframe.Team == dataframe.iloc[i,1]) & (dataframe.Date <= dataframe.iloc[i,5])].sort_values(by='Date', ascending = True).iloc[-number_of_games:]
        
        if len(team_df) > 1 and len(opponent_df) > 1:
            
            # Team Data
            attributes = []
            metrics = []
            team_current_game = team_df.iloc[-1:] # Create a dataframe containing information about the ith game of the input dataframe 
            team_df = team_df.drop(team_df.index[-1:]) # Modify the previously created team_df by removing the last row, which is the "current game"
            
            # Loop over each column of team_df, taking the average of numeric features and adding them to a list
            for column in team_df.columns:
                if column == 'Team' or column == 'Opponent' or column == 'Date' or column == 'Time' or column == 'Location' or column == 'Season' or column == 'Playoff' or column == 'Home' or column == 'Win':
                    attributes.append(team_current_game.iloc[0][column])
                else:
                    metrics.append(np.mean(team_df[column]))
            team = attributes + metrics
            
            # Opponent Data
            opponent = [] 
            opponent_df = opponent_df.drop(opponent_df.index[-1:])
        
            # Loop over each column of opponent_df, taking the average of numeric features and adding them to a list
            # Notice: String attributes are NOT added to the list
            for column in opponent_df.columns:
                if column == 'Team' or column == 'Opponent' or column == 'Date' or column == 'Time' or column == 'Location' or column == 'Season' or column == 'Playoff' or column == 'Team-Score' or column == "Opponent-Score" or column == "Home" or column == 'Win':
                    None
                else:
                    opponent.append(np.mean(opponent_df[column]))
            
            # Target Data
            target = []
            for column in team_current_game.columns:
                if column == 'Team-Score' or column == 'Opponent-Score':
                    target.append(team_current_game.iloc[0][column])
        
            row = team + opponent + target

            # Combine
            games.append(row)
            
    # The following block of code creates a list to be used as column names
    team_attributes = ['Team', 'Opponent', 'Win', 'Date', 'Time', 'Location', 'Season', 'Playoff', 'Home']
    opp_attributes = ['Team', 'Opponent', 'Win', 'Date', 'Time', 'Location', 'Season', 'Playoff', 'Home', 'Team-Score', 'Opponent-Score']
    team_metrics = list(df_12_13.columns)
    for i in range(0, len(team_attributes)):
        team_metrics.remove(team_attributes[i])
    opp_metrics = list(df_12_13.columns)
    for i in range(0, len(opp_attributes)):
        opp_metrics.remove(opp_attributes[i])
    for i in range(0, len(team_metrics)): # Add the prefix "avg_team" to indicate these are averages
        team_metrics[i] = "avg_team_" + team_metrics[i]
    for i in range(0, len(opp_metrics)): # Add the prefix "avg_opp" to indicate these are averages
        opp_metrics[i] = "avg_opp_" + opp_metrics[i]
    column_names = team_attributes + team_metrics + opp_metrics + ['Team-Score', 'Opponent-Score']
    
    # Create DataFrame
    nba_df = pd.DataFrame(games, columns = column_names)
    nba_df = nba_df.drop(['Playoff'], axis = 1) # Remove the playoff dummy, since we already filtered out playoff games
        
    return nba_df

In [37]:
# AVERAGE Regular Season (Non-Playoff) Games
number_of_games = 3
df_12_13_avg = get_averages(df_12_13, number_of_games)
df_13_14_avg = get_averages(df_13_14, number_of_games)
df_14_15_avg = get_averages(df_14_15, number_of_games)
df_15_16_avg = get_averages(df_15_16, number_of_games)
df_16_17_avg = get_averages(df_16_17, number_of_games)

In [38]:
# Write to CSV
os.chdir("/Users/erikgregorywebb/Documents/Python/nba-prediction/Preprocessing/Data")
df_12_13_avg.to_csv("df_12_13_avg.csv", index = False)
df_13_14_avg.to_csv("df_13_14_avg.csv", index = False)
df_14_15_avg.to_csv("df_14_15_avg.csv", index = False)
df_15_16_avg.to_csv("df_15_16_avg.csv", index = False)
df_16_17_avg.to_csv("df_16_17_avg.csv", index = False)
os.chdir("/Users/erikgregorywebb/Documents/Python/nba-prediction")

### Create Team Rank Variable

In [39]:
def add_rank(dataframe1, dataframe2):
    # Determine team rank by the average number of wins in a season 
    teams = list(dataframe1.groupby(['Team']).mean()['Win'].rank(ascending = False).index)
    rank = list(dataframe1.groupby(['Team']).mean()['Win'].rank(ascending = False).values)
    max_value = max(rank)
    position = len(dataframe2.columns)
    
    # Create a new column in output dataframe called 'Rank'
    dataframe2['Rank'] = ""
    for i in range(0, len(dataframe2)):
        val = dataframe2.iloc[i, 1]
        try: 
            index_val = teams.index(val)
            dataframe2.iloc[i, position] = rank[index_val]
        except:
            dataframe2.iloc[i, position] = max_value
    return dataframe2

In [40]:
df_13_14_avg = add_rank(df_12_13_avg, df_13_14_avg)
df_14_15_avg = add_rank(df_13_14_avg, df_14_15_avg)
df_15_16_avg = add_rank(df_14_15_avg, df_15_16_avg)
df_16_17_avg = add_rank(df_15_16_avg, df_16_17_avg)

In [41]:
df_13_14_avg.head(3)

,Team,Opponent,Win,Date,Time,Location,Season,Home,avg_team_Team-Score,avg_team_Opponent-Score,avg_team_FG,avg_team_FGA,avg_team_FG%,avg_team_3P,avg_team_3PA,avg_team_3P%,avg_team_FT,avg_team_FTA,avg_team_FT%,avg_team_ORB,avg_team_DRB,avg_team_TRB,avg_team_AST,avg_team_STL,avg_team_BLK,avg_team_TOV,avg_team_PF,avg_team_TS%,avg_team_eFG%,avg_team_3PAr,avg_team_FTr,avg_team_ORB%,avg_team_DRB%,avg_team_TRB%,avg_team_AST%,avg_team_STL%,avg_team_BLK%,avg_team_TOV%,avg_team_ORtg,avg_team_DRtg,avg_opp_FG,avg_opp_FGA,avg_opp_FG%,avg_opp_3P,avg_opp_3PA,avg_opp_3P%,avg_opp_FT,avg_opp_FTA,avg_opp_FT%,avg_opp_ORB,avg_opp_DRB,avg_opp_TRB,avg_opp_AST,avg_opp_STL,avg_opp_BLK,avg_opp_TOV,avg_opp_PF,avg_opp_TS%,avg_opp_eFG%,avg_opp_3PAr,avg_opp_FTr,avg_opp_ORB%,avg_opp_DRB%,avg_opp_TRB%,avg_opp_AST%,avg_opp_STL%,avg_opp_BLK%,avg_opp_TOV%,avg_opp_ORtg,avg_opp_DRtg,Team-Score,Opponent-Score,Rank
0,Los Angeles Clippers,Golden State Warriors,1,2013-10-31,10:30 PM,"STAPLES Center, Los Angeles, California",2013-14,1,103.0,116.0,41.0,83.0,0.494,8.0,21.0,0.381,13.0,23.0,0.565,10.0,30.0,40.0,27.0,11.0,4.0,16.0,21.0,0.553,0.542,0.253,0.277,22.7,62.5,43.5,65.9,11.0,6.3,14.7,102.6,115.6,46.0,86.0,0.535,15.0,27.0,0.556,18.0,23.0,0.783,7.0,41.0,48.0,34.0,8.0,9.0,15.0,22.0,0.650,0.622,0.314,0.267,18.9,82.0,55.2,73.9,7.8,12.7,13.5,121.9,91.7,126,115,10
1,Chicago Bulls,New York Knicks,1,2013-10-31,8:00 PM,"United Center, Chicago, Illinois",2013-14,1,95.0,107.0,35.0,83.0,0.422,7.0,26.0,0.269,18.0,23.0,0.783,11.0,30.0,41.0,23.0,11.0,4.0,18.0,27.0,0.510,0.464,0.313,0.277,23.9,85.7,50.6,65.7,11.3,7.7,16.2,97.9,110.2,36.0,71.0,0.507,3.0,13.0,0.231,15.0,17.0,0.882,6.0,28.0,34.0,17.0,12.0,6.0,22.0,16.0,0.573,0.528,0.183,0.239,18.8,84.8,52.3,47.2,12.8,10.3,21.9,95.7,88.3,82,81,7
2,Golden State Warriors,Los Angeles Clippers,0,2013-10-31,10:30 PM,"STAPLES Center, Los Angeles, California",2013-14,0,125.0,94.0,46.0,86.0,0.535,15.0,27.0,0.556,18.0,23.0,0.783,7.0,41.0,48.0,34.0,8.0,9.0,15.0,22.0,0.650,0.622,0.314,0.267,18.9,82.0,55.2,73.9,7.8,12.7,13.5,121.9,91.7,41.0,83.0,0.494,8.0,21.0,0.381,13.0,23.0,0.565,10.0,30.0,40.0,27.0,11.0,4.0,16.0,21.0,0.553,0.542,0.253,0.277,22.7,62.5,43.5,65.9,11.0,6.3,14.7,102.6,115.6,115,126,6

In [42]:
# Combine 2013-14, 2014-15, and 2015-15 seasons to form training dataset
frames = [df_13_14_avg, df_14_15_avg, df_15_16_avg]
train = pd.concat(frames)
test = df_16_17_avg

os.chdir("/Users/erikgregorywebb/Documents/Python/nba-prediction/Modeling")
train.to_csv("train.csv", index = False)
test.to_csv("test.csv", index = False)